Update MLFlow-distilbert-base-cased-distilled-squad.yml

diff --git a/.github/workflows/MLFlow-distilbert-base-cased-distilled-squad.yml b/.github/workflows/MLFlow-distilbert-base-cased-distilled-squad.yml
--- a/.github/workflows/MLFlow-distilbert-base-cased-distilled-squad.yml
+++ b/.github/workflows/MLFlow-distilbert-base-cased-distilled-squad.yml
@@ -1,4 +1,4 @@
-name: MLFlow-distilbert-base-cased-distilled-squad
+name: distilbert-base-cased-distilled-squad
 
 on: 
   workflow_dispatch:
@@ -7,8 +7,8 @@ env:
   test_model_name: distilbert-base-cased-distilled-squad
   test_sku_type: cpu
   test_trigger_next_model: true
-  test_queue: test-northeurope-3
-  test_set: huggingface-all
+  test_queue: test-sonata-ws-eus-1
+  test_set: HF
   test_keep_looping: false
 
 jobs:
@@ -20,7 +20,7 @@ jobs:
     - name: azure-login-step
       uses: azure/login@v1
       with:
-        creds: ${{secrets.AZ_CRED}}
+        creds: ${{secrets.TEST_WS_CRED}}
     - name: pip-install-azure-ai-ml
       run: pip install azure-ai-ml
     - name: pip-install-azureml-core
@@ -42,13 +42,15 @@ jobs:
     - name: pip-install-sentencepiece
       run: pip install sentencepiece
     - name: pip-install-fugashi[unidic-lite]
-      run: pip install fugashi[unidic-lite]  
+      run: pip install fugashi[unidic-lite]
+    - name: pip-install-datasets
+      run: pip install datasets
     - name: deploy-model-step
       id: deploy-model-step
       run: python generic_initial_automation.py
-      working-directory: tests/src/automation_for_constant_library
-    - name: trigger-next-model-step
-      env:
-        GITHUB_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
-      if: ${{ env.test_trigger_next_model == 'true' && steps.deploy-model-step.outputs.NEXT_MODEL != '' && (success() || failure())}}
-      run: gh workflow run ${{ steps.deploy-model-step.outputs.NEXT_MODEL }} --ref ${{ github.ref_name }}
+      working-directory: tests/src/automation_for_constant_library/
+    # - name: trigger-next-model-step
+    #   env:
+    #     GITHUB_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
+    #   if: ${{ env.test_trigger_next_model == 'true' && steps.deploy-model-step.outputs.NEXT_MODEL != '' && (success() || failure())}}
+    #   run: gh workflow run ${{ steps.deploy-model-step.outputs.NEXT_MODEL }} --ref ${{ github.ref_name }}
