Update MLFlow-t5-small.yml

diff --git a/.github/workflows/MLFlow-t5-small.yml b/.github/workflows/MLFlow-t5-small.yml
--- a/.github/workflows/MLFlow-t5-small.yml
+++ b/.github/workflows/MLFlow-t5-small.yml
@@ -1,13 +1,13 @@
-name: MLFlow-t5-small
+name: t5-small
 
 on: 
   workflow_dispatch:
 
 env:
-  test_model_name: t5-small
+  # test_model_name: t5-small
   test_sku_type: cpu
-  test_trigger_next_model: true
-  test_queue: test-northeurope-4.json
+  # test_trigger_next_model: true
+  test_queue: test-sonata-ws-eus-0
   test_set: huggingface-all
   test_keep_looping: false
 
@@ -47,10 +47,10 @@ jobs:
       run: pip install datasets
     - name: deploy-model-step
       id: deploy-model-step
-      run: python generic_pipeline_component.py
-      working-directory: tests/src/pipeline_component
-    - name: trigger-next-model-step
-      env:
-        GITHUB_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
-      if: ${{ env.test_trigger_next_model == 'true' && steps.deploy-model-step.outputs.NEXT_MODEL != '' && (success() || failure())}}
-      run: gh workflow run ${{ steps.deploy-model-step.outputs.NEXT_MODEL }} --ref ${{ github.ref_name }}
+      run: python generic_initial_automation.py
+      working-directory: tests/src/automation_for_constant_library/
+    # - name: trigger-next-model-step
+    #   env:
+    #     GITHUB_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
+    #   if: ${{ env.test_trigger_next_model == 'true' && steps.deploy-model-step.outputs.NEXT_MODEL != '' && (success() || failure())}}
+    #   run: gh workflow run ${{ steps.deploy-model-step.outputs.NEXT_MODEL }} --ref ${{ github.ref_name }}
