Update MLFlow-Import-distilbert-base-cased-distilled-squad.yml

diff --git a/.github/workflows/MLFlow-Import-distilbert-base-cased-distilled-squad.yml b/.github/workflows/MLFlow-Import-distilbert-base-cased-distilled-squad.yml
--- a/.github/workflows/MLFlow-Import-distilbert-base-cased-distilled-squad.yml
+++ b/.github/workflows/MLFlow-Import-distilbert-base-cased-distilled-squad.yml
@@ -4,9 +4,9 @@ on:
   workflow_dispatch:
 
 env:
-  test_model_name: distilbert-base-cased-distilled-squad
+  # test_model_name: distilbert-base-cased-distilled-squad
   test_sku_type: cpu
-  test_trigger_next_model: true
+  # test_trigger_next_model: true
   test_queue: test-sonata-ws-eus-1
   test_set: HF
   test_keep_looping: false
@@ -47,10 +47,10 @@ jobs:
       run: pip install datasets
     - name: deploy-model-step
       id: deploy-model-step
-      run: python generic_pipeline_automation.py
+      run: python testmodel.py
       working-directory: tests/src/pipeline_component_automation
-    - name: trigger-next-model-step
-      env:
-        GITHUB_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
-      if: ${{ env.test_trigger_next_model == 'true' && steps.deploy-model-step.outputs.NEXT_MODEL != '' && (success() || failure())}}
-      run: gh workflow run ${{ steps.deploy-model-step.outputs.NEXT_MODEL }} --ref ${{ github.ref_name }}
+    # - name: trigger-next-model-step
+    #   env:
+    #     GITHUB_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
+    #   if: ${{ env.test_trigger_next_model == 'true' && steps.deploy-model-step.outputs.NEXT_MODEL != '' && (success() || failure())}}
+    #   run: gh workflow run ${{ steps.deploy-model-step.outputs.NEXT_MODEL }} --ref ${{ github.ref_name }}
