Update MLFlow-meta-llama-Llama-2-13b-chat-hf.yml

diff --git a/.github/workflows/MLFlow-meta-llama-Llama-2-13b-chat-hf.yml b/.github/workflows/MLFlow-meta-llama-Llama-2-13b-chat-hf.yml
--- a/.github/workflows/MLFlow-meta-llama-Llama-2-13b-chat-hf.yml
+++ b/.github/workflows/MLFlow-meta-llama-Llama-2-13b-chat-hf.yml
@@ -47,8 +47,8 @@ jobs:
       id: deploy-model-step
       run: python testing_automation.py
       working-directory: tests/src/automation_for_constant_library
-    - name: trigger-next-model-step
-      env:
-        GITHUB_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
-      if: ${{ env.test_trigger_next_model == 'true' && steps.deploy-model-step.outputs.NEXT_MODEL != '' && (success() || failure())}}
-      run: gh workflow run ${{ steps.deploy-model-step.outputs.NEXT_MODEL }} --ref ${{ github.ref_name }}
+    # - name: trigger-next-model-step
+    #   env:
+    #     GITHUB_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
+    #   if: ${{ env.test_trigger_next_model == 'true' && steps.deploy-model-step.outputs.NEXT_MODEL != '' && (success() || failure())}}
+    #   run: gh workflow run ${{ steps.deploy-model-step.outputs.NEXT_MODEL }} --ref ${{ github.ref_name }}
