Update multi-models-deploy.yml

diff --git a/.github/workflows/multi-models-deploy.yml b/.github/workflows/multi-models-deploy.yml
--- a/.github/workflows/multi-models-deploy.yml
+++ b/.github/workflows/multi-models-deploy.yml
@@ -6,13 +6,12 @@ on:
       model_list:
         description: 'List of models to deploy'
         required: true
-      test_model_name:
-        description: 'Name of the model to deploy'
-        required: true
+      # test_model_name:
+      #   description: 'Name of the model to deploy'
+      #   required: true
 
 env:
   test_sku_type: cpu
-  #test_queue: test-southcentralus-22
   test_set: huggingface-all
   test_keep_looping: false
   workspace: test-southcentralus
@@ -76,13 +75,36 @@ jobs:
       - name: pip-install-fugashi[unidic-lite]
         run: pip install fugashi[unidic-lite]  
 
-      - name: deploy-model-step
-        id: deploy-model-step
-        run: python generic_model_download_and_register.py ${{ matrix.model }}
+      # - name: deploy-model-step
+      #   id: deploy-model-step
+      #   run: python generic_model_download_and_register.py ${{ matrix.model }}
+      #   working-directory: tests/src/automation_for_constant_library
+
+      # - name: trigger-next-model-step
+      #   env:
+      #     GITHUB_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
+      #   if: ${{ env.test_trigger_next_model == 'true' && steps.deploy-model-step.outputs.NEXT_MODEL != '' && (success() || failure())}}
+      #   run: gh workflow run ${{ steps.deploy-model-step.outputs.NEXT_MODEL }} --ref ${{ github.ref_name }}
+
+      - name: deploy-models
+        id: deploy-models
+        run: |
+          # Get the model list from the input
+          model_list=$INPUT_MODEL_LIST
+          
+          # Split the model list into an array
+          IFS=',' read -ra models <<< "$model_list"
+          
+          # Loop through the models and deploy each one
+          for model in "${models[@]}"; do
+            python generic_model_download_and_register.py $model
+          done
+        env:
+          INPUT_MODEL_LIST: ${{fromJson(inputs.model_list)}}
         working-directory: tests/src/automation_for_constant_library
 
       - name: trigger-next-model-step
         env:
           GITHUB_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
-        if: ${{ env.test_trigger_next_model == 'true' && steps.deploy-model-step.outputs.NEXT_MODEL != '' && (success() || failure())}}
+        if: ${{ env.test_trigger_next_model == 'true' && steps.deploy-models.outcome == 'success' }}
         run: gh workflow run ${{ steps.deploy-model-step.outputs.NEXT_MODEL }} --ref ${{ github.ref_name }}
