Update multi-models-deploy.yml

diff --git a/.github/workflows/multi-models-deploy.yml b/.github/workflows/multi-models-deploy.yml
--- a/.github/workflows/multi-models-deploy.yml
+++ b/.github/workflows/multi-models-deploy.yml
@@ -9,7 +9,6 @@ on:
 
 
 env:
-  #test_model_name: ${{ matrix.model }}
   test_sku_type: cpu
   test_set: huggingface-all
   test_keep_looping: false
@@ -82,8 +81,14 @@ jobs:
         run: python generic_model_download_and_register.py ${{ matrix.model }}
         working-directory: tests/src/automation_for_constant_library
 
-      - name: trigger-next-model-step
+      - name: handle-deploy-model-failure
+        if: failure()
+        continue-on-error: true
+        run: echo "Deployment failed for ${{ matrix.model }}"
+
+
+      #- name: trigger-next-model-step
         env:
           GITHUB_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
-        if: ${{ env.test_trigger_next_model == 'true' && steps.deploy-model-step.outputs.NEXT_MODEL != '' && (success() || failure())}}
-        run: gh workflow run ${{ steps.deploy-model-step.outputs.NEXT_MODEL }} --ref ${{ github.ref_name }}
+        # if: ${{ env.test_trigger_next_model == 'true' && steps.deploy-model-step.outputs.NEXT_MODEL != '' && (success() || failure())}}
+        # run: gh workflow run ${{ steps.deploy-model-step.outputs.NEXT_MODEL }} --ref ${{ github.ref_name }}
